#!/bin/bash
echo "SOURCE_COMMIT: $SOURCE_COMMIT"
if [[ -z "$SOURCE_COMMIT" ]]; then
    export SOURCE_COMMIT="${SOURCE_COMMIT:-$(git rev-parse HEAD)}"
    echo "Updating SOURCE_COMMIT from git rev-parse HEAD"
    echo "SOURCE_COMMIT: $SOURCE_COMMIT"
fi

echo "SCHEMA_HASH: $SCHEMA_HASH"
if [[ -z "$SCHEMA_HASH" ]]; then
    export SCHEMA_HASH="${SCHEMA_HASH:-$(shasum hive/db/schema.py | cut -c1-8)}"
    echo "Updating SCHEMA_HASH from sha1 of hive/db/schema.py"
    echo "SCHEMA_HASH: $SCHEMA_HASH"
fi

docker build -t "${IMAGE_NAME}" --build-arg SOURCE_COMMIT="${SOURCE_COMMIT}"  --build-arg SCHEMA_HASH="${SCHEMA_HASH}" --build-arg DOCKER_TAG="${DOCKER_TAG}" .
